# Set update schedule for GitHub Actions and pre-commit

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "clang-format"
